name: toko_plastik_rizky
version: 1.0.0+1
description: Aplikasi Manajemen Gudang dan SKU untuk Toko Plastik Rizky
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.10
  http: ^0.13.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
